[2023-09-15T20:28:35.145+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:28:28.535099+00:00 [queued]>
[2023-09-15T20:28:35.155+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:28:28.535099+00:00 [queued]>
[2023-09-15T20:28:35.156+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:28:35.156+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-15T20:28:35.156+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:28:35.172+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-15 20:28:28.535099+00:00
[2023-09-15T20:28:35.176+0000] {standard_task_runner.py:55} INFO - Started process 278 to run task
[2023-09-15T20:28:35.178+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'tsk4', 'manual__2023-09-15T20:28:28.535099+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmppw6p0kiy']
[2023-09-15T20:28:35.179+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask tsk4
[2023-09-15T20:28:35.240+0000] {task_command.py:388} INFO - Running <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:28:28.535099+00:00 [running]> on host 586b349287a0
[2023-09-15T20:28:35.317+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=danilodias_lc@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-15T20:28:28.535099+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-15T20:28:28.535099+00:00
[2023-09-15T20:28:35.318+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-15T20:28:35.319+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-15T20:28:35.327+0000] {subprocess.py:86} INFO - Output:
[2023-09-15T20:28:35.329+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-15T20:28:35.341+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-15T20:28:35.344+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=tsk4, execution_date=20230915T202828, start_date=20230915T202835, end_date=20230915T202835
[2023-09-15T20:28:35.364+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 278)
[2023-09-15T20:28:35.390+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-15T20:28:35.417+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
