[2023-09-14T19:54:07.622+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:54:06.869673+00:00 [queued]>
[2023-09-14T19:54:07.636+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:54:06.869673+00:00 [queued]>
[2023-09-14T19:54:07.636+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:54:07.636+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-14T19:54:07.636+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:54:07.656+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2023-09-14 19:54:06.869673+00:00
[2023-09-14T19:54:07.660+0000] {standard_task_runner.py:55} INFO - Started process 9007 to run task
[2023-09-14T19:54:07.663+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag2', 'task1', 'manual__2023-09-14T19:54:06.869673+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag2.py', '--cfg-path', '/tmp/tmpo9wnbrm5']
[2023-09-14T19:54:07.663+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask task1
[2023-09-14T19:54:07.728+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:54:06.869673+00:00 [running]> on host 8cc0db633803
[2023-09-14T19:54:07.802+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2023-09-14T19:54:06.869673+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-14T19:54:06.869673+00:00
[2023-09-14T19:54:07.803+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-14T19:54:07.804+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-14T19:54:07.813+0000] {subprocess.py:86} INFO - Output:
[2023-09-14T19:54:07.815+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-14T19:54:07.827+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-14T19:54:07.831+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag2, task_id=task1, execution_date=20230914T195406, start_date=20230914T195407, end_date=20230914T195407
[2023-09-14T19:54:07.848+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 9007)
[2023-09-14T19:54:07.874+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-14T19:54:07.898+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
