[2023-09-14T19:53:35.194+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:53:33.983484+00:00 [queued]>
[2023-09-14T19:53:35.203+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:53:33.983484+00:00 [queued]>
[2023-09-14T19:53:35.203+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:53:35.203+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-14T19:53:35.203+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:53:35.219+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2023-09-14 19:53:33.983484+00:00
[2023-09-14T19:53:35.223+0000] {standard_task_runner.py:55} INFO - Started process 8956 to run task
[2023-09-14T19:53:35.226+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag2', 'task1', 'manual__2023-09-14T19:53:33.983484+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag2.py', '--cfg-path', '/tmp/tmpqwhggm1r']
[2023-09-14T19:53:35.226+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask task1
[2023-09-14T19:53:35.285+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag2.task1 manual__2023-09-14T19:53:33.983484+00:00 [running]> on host 8cc0db633803
[2023-09-14T19:53:35.358+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2023-09-14T19:53:33.983484+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-14T19:53:33.983484+00:00
[2023-09-14T19:53:35.359+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-14T19:53:35.360+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-14T19:53:35.368+0000] {subprocess.py:86} INFO - Output:
[2023-09-14T19:53:35.369+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-14T19:53:35.380+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-14T19:53:35.384+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag2, task_id=task1, execution_date=20230914T195333, start_date=20230914T195335, end_date=20230914T195335
[2023-09-14T19:53:35.398+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 8956)
[2023-09-14T19:53:35.437+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-14T19:53:35.458+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
