[2023-09-14T19:56:35.181+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag3.task2 manual__2023-09-14T19:56:34.311208+00:00 [queued]>
[2023-09-14T19:56:35.191+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag3.task2 manual__2023-09-14T19:56:34.311208+00:00 [queued]>
[2023-09-14T19:56:35.191+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:56:35.191+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-14T19:56:35.191+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-14T19:56:35.209+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task2> on 2023-09-14 19:56:34.311208+00:00
[2023-09-14T19:56:35.213+0000] {standard_task_runner.py:55} INFO - Started process 9181 to run task
[2023-09-14T19:56:35.216+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag3', 'task2', 'manual__2023-09-14T19:56:34.311208+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag3.py', '--cfg-path', '/tmp/tmpi9nykstx']
[2023-09-14T19:56:35.217+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask task2
[2023-09-14T19:56:35.277+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag3.task2 manual__2023-09-14T19:56:34.311208+00:00 [running]> on host 8cc0db633803
[2023-09-14T19:56:35.351+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag3
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2023-09-14T19:56:34.311208+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-14T19:56:34.311208+00:00
[2023-09-14T19:56:35.352+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-14T19:56:35.353+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-14T19:56:35.362+0000] {subprocess.py:86} INFO - Output:
[2023-09-14T19:56:35.363+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-14T19:56:35.374+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-14T19:56:35.378+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag3, task_id=task2, execution_date=20230914T195634, start_date=20230914T195635, end_date=20230914T195635
[2023-09-14T19:56:35.393+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 9181)
[2023-09-14T19:56:35.427+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-14T19:56:35.458+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
